spring:
  application:
    name: maybatis-tot-demo
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://10.1.84.60:3306/blogdatabase?useUnicode=true&amp;characterEncoding=utf8
    username: root
    password: root